<?php
/**
 * Offline regression test for wallet-address validation (NMM_Address via
 * NMM_Cryptocurrencies::is_valid_wallet_address).
 *
 * What this pins (the P0 finding it guards against): the old per-coin checks
 * were unanchored, checksum-free preg_matches, so all of the following were
 * ACCEPTED and would silently collect customer funds into unspendable
 * outputs: truncated BTC addresses, 'addr?x=1' (query injection into the
 * explorer URLs), 'hello bc1q...' (ungrouped alternation matched anywhere),
 * and bad-checksum DOGE addresses. Every one of those classes must fail now:
 *
 *  - base58check coins (BTC/LTC/DOGE/DASH/BCH-legacy/DGB/QTUM/XMY/BTX/TRX/..):
 *    real base58 decode + double-SHA256 4-byte checksum + version byte.
 *  - bech32/bech32m (BIP-173/350): checksum, no mixed case, witness rules.
 *  - CashAddr (BCH): polymod checksum, with/without 'bitcoincash:' prefix.
 *  - pattern-only coins (ETH/XRP/XMR/SOL/...): anchored ^...$ regexes.
 *
 * TAPROOT DECISION: witness v1 'bc1p...' (bech32m) IS ACCEPTED for merchant
 * wallet addresses. These are Classic/Autopay RECEIVING addresses - any
 * modern wallet can pay a taproot output, and the verification explorers the
 * plugin queries (mempool.space, blockstream.info, blockcypher) all index
 * them. Rejecting them would push merchants with modern wallets back to
 * address reuse on legacy formats for no safety benefit. Witness v0 encoded
 * as bech32m, and v1 encoded as bech32, are rejected per BIP-350.
 *
 * Test-vector strategy: valid vectors are either (a) well-known public
 * reference addresses, (b) the independently verified zero-hash160 addresses
 * pinned by tests/test-hd-addrtype.php, or (c) generated by the tiny
 * encoders below - which are themselves cross-checked against known-good
 * strings ('1111111111111111111114oLvT2', the BIP-173 P2WPKH example) before
 * any generated vector is trusted. Invalid vectors (mutation / truncation /
 * affix / wrong network / wrong case) are derived mechanically from the
 * valid ones so every coin gets the same hostile treatment.
 *
 * Usage: php tests/test-address-validation.php   (pure PHP, no network,
 *        no GMP/BCMath required - the validator is deliberately extension-free)
 */

require __DIR__ . '/wp-stubs.php';

class NMM_Util {
	public static function p_enabled() { return false; }
	public static function log($f, $l, $m, $level = 'info') {}
}

$root = dirname(__DIR__);
require $root . '/src/vendor/CashAddress.php'; // used to cross-generate a CashAddr vector
require $root . '/src/NMM_Cryptocurrency.php';
require $root . '/src/NMM_Cryptocurrencies.php';
require $root . '/src/NMM_Address.php';

$failed = false;
$nChecks = 0;

function aok($label, $cond, $extra = '') {
	global $failed, $nChecks;
	$nChecks++;
	printf("%-74s %s%s\n", $label, $cond ? 'ok' : 'FAIL', ($cond || $extra === '') ? '' : "  ($extra)");
	if (!$cond) {
		$failed = true;
	}
}

function check($cryptoId, $address, $expected, $note) {
	$got = (bool) NMM_Cryptocurrencies::is_valid_wallet_address($cryptoId, $address);
	aok($cryptoId . ' ' . $note . ': ' . substr($address, 0, 44), $got === $expected,
		'want ' . ($expected ? 'valid' : 'invalid') . ', got ' . ($got ? 'valid' : 'invalid'));
}

// ---------------------------------------------------------------------
// test-side encoders (independent implementations, cross-checked below)
// ---------------------------------------------------------------------

function t_b58check_encode($versionPrefix, $hash) {
	$payload = $versionPrefix . $hash;
	$full = $payload . substr(hash('sha256', hash('sha256', $payload, true), true), 0, 4);

	$alphabet = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
	$digits = array(0);
	for ($i = 0, $len = strlen($full); $i < $len; $i++) {
		$carry = ord($full[$i]);
		for ($j = 0, $n = count($digits); $j < $n; $j++) {
			$carry += $digits[$j] << 8;
			$digits[$j] = $carry % 58;
			$carry = intdiv($carry, 58);
		}
		while ($carry > 0) {
			$digits[] = $carry % 58;
			$carry = intdiv($carry, 58);
		}
	}
	$out = '';
	for ($i = 0; $i < strlen($full) && $full[$i] === "\x00"; $i++) {
		$out .= '1';
	}
	for ($i = count($digits) - 1; $i >= 0; $i--) {
		$out .= $alphabet[$digits[$i]];
	}
	return $out;
}

function t_bech32_polymod($values) {
	$gen = array(0x3b6a57b2, 0x26508e6d, 0x1ea119fa, 0x3d4233dd, 0x2a1462b3);
	$chk = 1;
	foreach ($values as $v) {
		$top = $chk >> 25;
		$chk = (($chk & 0x1ffffff) << 5) ^ $v;
		for ($i = 0; $i < 5; $i++) {
			if (($top >> $i) & 1) {
				$chk ^= $gen[$i];
			}
		}
	}
	return $chk;
}

function t_bech32_encode($hrp, $witnessVersion, $programBytes, $useBech32m) {
	$charset = 'qpzry9x8gf2tvdw0s3jn54khce6mua7l';

	// 8-bit -> 5-bit with padding
	$data = array($witnessVersion);
	$acc = 0; $bits = 0;
	for ($i = 0, $len = strlen($programBytes); $i < $len; $i++) {
		$acc = ($acc << 8) | ord($programBytes[$i]);
		$bits += 8;
		while ($bits >= 5) {
			$bits -= 5;
			$data[] = ($acc >> $bits) & 31;
		}
	}
	if ($bits > 0) {
		$data[] = ($acc << (5 - $bits)) & 31;
	}

	$hrpExp = array();
	for ($i = 0; $i < strlen($hrp); $i++) { $hrpExp[] = ord($hrp[$i]) >> 5; }
	$hrpExp[] = 0;
	for ($i = 0; $i < strlen($hrp); $i++) { $hrpExp[] = ord($hrp[$i]) & 31; }

	$const = $useBech32m ? 0x2bc830a3 : 1;
	$poly = t_bech32_polymod(array_merge($hrpExp, $data, array(0, 0, 0, 0, 0, 0))) ^ $const;
	$checksum = array();
	for ($i = 0; $i < 6; $i++) {
		$checksum[] = ($poly >> (5 * (5 - $i))) & 31;
	}

	$out = $hrp . '1';
	foreach (array_merge($data, $checksum) as $d) {
		$out .= $charset[$d];
	}
	return $out;
}

// CashAddr encoder (40-bit polymod, distinct from bech32's 30-bit one), so
// token-aware vectors can be generated rather than copied. Self-checked below
// by reproducing the type-0 spec vector from the same hash.
function t_cashaddr_encode($prefix, $type, $hash) {
	$charset = 'qpzry9x8gf2tvdw0s3jn54khce6mua7l';
	$sizeBits = array(20 => 0, 24 => 1, 28 => 2, 32 => 3, 40 => 4, 48 => 5, 56 => 6, 64 => 7);
	$payload = chr(($type << 3) | $sizeBits[strlen($hash)]) . $hash;

	$data = array(); $acc = 0; $bits = 0;
	for ($i = 0, $len = strlen($payload); $i < $len; $i++) {
		$acc = ($acc << 8) | ord($payload[$i]);
		$bits += 8;
		while ($bits >= 5) { $bits -= 5; $data[] = ($acc >> $bits) & 31; }
	}
	if ($bits > 0) { $data[] = ($acc << (5 - $bits)) & 31; }

	$pre = array();
	for ($i = 0; $i < strlen($prefix); $i++) { $pre[] = ord($prefix[$i]) & 31; }
	$pre[] = 0;

	$c = 1;
	foreach (array_merge($pre, $data, array(0, 0, 0, 0, 0, 0, 0, 0)) as $d) {
		$c0 = $c >> 35;
		$c = (($c & 0x07ffffffff) << 5) ^ $d;
		if ($c0 & 0x01) { $c ^= 0x98f2bc8e61; }
		if ($c0 & 0x02) { $c ^= 0x79b76d99e2; }
		if ($c0 & 0x04) { $c ^= 0xf33e5fb3c4; }
		if ($c0 & 0x08) { $c ^= 0xae2eabe2a8; }
		if ($c0 & 0x10) { $c ^= 0x1e4f43e470; }
	}
	$poly = $c ^ 1;

	$out = '';
	foreach ($data as $d) { $out .= $charset[$d]; }
	for ($i = 0; $i < 8; $i++) { $out .= $charset[($poly >> (5 * (7 - $i))) & 31]; }
	return $prefix . ':' . $out;
}

// mutate one character (index from the end) within the given charset
function t_mutate($address, $charset, $fromEnd = 3) {
	$i = strlen($address) - $fromEnd;
	$replacement = $charset[(strpos($charset, $address[$i]) + 1) % strlen($charset)];
	$address[$i] = $replacement;
	return $address;
}

// ---------------------------------------------------------------------
// encoder self-checks against independently known-good strings
// ---------------------------------------------------------------------

$zeros20 = str_repeat("\x00", 20);
$bip173Program = hex2bin('751e76e8199196d454941c45d1b3a323f1433bd6');

aok('test encoder: b58check(0x00, zeros20) matches pinned addrtype vector',
	t_b58check_encode("\x00", $zeros20) === '1111111111111111111114oLvT2');
aok('test encoder: b58check(0x1e, zeros20) matches pinned DOGE vector',
	t_b58check_encode("\x1e", $zeros20) === 'D596YFweJQuHY1BbjazZYmAbt8jJPbKehC');
aok('test encoder: bech32(bc, v0, BIP-173 program) matches BIP-173 vector',
	t_bech32_encode('bc', 0, $bip173Program, false) === 'bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4');

// hash160 behind the CashAddr spec pair, recovered from the spec vector so the
// token-aware vectors below are the SAME key in a different address type.
$cashAddrSpecHash = hex2bin('76a04053bda0a88bda5177b86a15c3b29f559873');
aok('test encoder: cashaddr(type 0) reproduces the CashAddr spec vector',
	t_cashaddr_encode('bitcoincash', 0, $cashAddrSpecHash) === 'bitcoincash:qpm2qsznhks23z7629mms6s4cwef74vcwvy22gdx6a');

// 32-byte x-only key for taproot vectors: the secp256k1 generator's X
$xonly = hex2bin('79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798');

// ---------------------------------------------------------------------
// registry coverage: every non-token coin must have a validation rule
// (a coin falling through to "return false" could never be configured)
// ---------------------------------------------------------------------

foreach (NMM_Cryptocurrencies::get() as $crypto) {
	if ($crypto->is_erc20_token()) {
		continue;
	}
	aok('registry coverage: ' . $crypto->get_id() . ' has a validation rule',
		NMM_Address::is_known($crypto->get_id()));
}

// unknown coin ids must keep throwing (historical contract)
$threw = false;
try {
	NMM_Cryptocurrencies::is_valid_wallet_address('NOPE', '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa');
}
catch (\Exception $e) {
	$threw = true;
}
aok('unknown cryptoId still throws', $threw);

// ---------------------------------------------------------------------
// per-scheme vector table
// scheme: b58 / bech32 / cashaddr / hex / pattern  (drives mutation charset)
// checksummed vectors additionally get mutation + truncation expectations
// ---------------------------------------------------------------------

$B58 = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
$B32 = 'qpzry9x8gf2tvdw0s3jn54khce6mua7l';
$HEX = '0123456789abcdef';

// [coin, address, scheme, note]
// every entry is a VALID mainnet address; hostile derivatives are generated
$valid = array(
	// BTC: genesis P2PKH, zero-hash P2PKH/P2SH (pinned by test-hd-addrtype),
	// BIP-173 P2WPKH, BIP-350 taproot, generated taproot, uppercase bech32
	array('BTC', '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa', 'b58', 'genesis P2PKH'),
	array('BTC', '1111111111111111111114oLvT2', 'b58', 'zero-hash P2PKH'),
	array('BTC', '31h1vYVSYuKP6AhS86fbRdMw9XHieotbST', 'b58', 'zero-hash P2SH'),
	array('BTC', 'bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4', 'bech32', 'BIP-173 P2WPKH'),
	array('BTC', 'BC1QW508D6QEJXTDG4Y5R3ZARVARY0C5XW7KV8F3T4', 'bech32-upper', 'all-upper bech32 (valid per BIP-173)'),
	array('BTC', 'bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqzk5jj0', 'bech32', 'BIP-350 taproot (witness v1, bech32m)'),
	array('BTC', t_bech32_encode('bc', 1, $xonly, true), 'bech32', 'generated taproot (bech32m)'),

	// LTC: pinned L/M forms, deprecated-but-spendable 3-form, generated ltc1
	array('LTC', 'LKDxGDJq5fF4FohAB8zJH24mDDNHDNtqsE', 'b58', 'zero-hash P2PKH (0x30)'),
	array('LTC', 'M7uAERuQW2AotfyLDyewFGcLUDtAYu9v5V', 'b58', 'zero-hash P2SH (0x32)'),
	array('LTC', '31h1vYVSYuKP6AhS86fbRdMw9XHieotbST', 'b58', 'legacy P2SH (0x05)'),
	array('LTC', t_bech32_encode('ltc', 0, $bip173Program, false), 'bech32', 'generated P2WPKH'),

	// DOGE
	array('DOGE', 'D596YFweJQuHY1BbjazZYmAbt8jJPbKehC', 'b58', 'zero-hash P2PKH (0x1e)'),
	array('DOGE', 'DH5yaieqoZN36fDVciNyRueRGvGLR3mr7L', 'b58', 'well-known P2PKH'),
	array('DOGE', t_b58check_encode("\x16", $zeros20), 'b58', 'generated P2SH (0x16)'),

	// DASH
	array('DASH', 'XagqqFetxiDb9wbartKDrXgnqLah6SqX2S', 'b58', 'zero-hash P2PKH (0x4c)'),
	array('DASH', t_b58check_encode("\x10", $zeros20), 'b58', 'generated P2SH (0x10)'),

	// BCH: legacy + CashAddr (spec vector pair) + library-generated + bare
	array('BCH', '1BpEi6DfDAUFd7GtittLSdBeYJvcoaVggu', 'b58', 'legacy P2PKH (spec pair)'),
	array('BCH', 'bitcoincash:qpm2qsznhks23z7629mms6s4cwef74vcwvy22gdx6a', 'cashaddr', 'CashAddr spec vector'),
	array('BCH', 'qpm2qsznhks23z7629mms6s4cwef74vcwvy22gdx6a', 'cashaddr', 'CashAddr without prefix'),
	array('BCH', \CashAddress\CashAddress::old2new('1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa'), 'cashaddr', 'library-generated from genesis'),
	array('BCH', strtoupper('bitcoincash:qpm2qsznhks23z7629mms6s4cwef74vcwvy22gdx6a'), 'cashaddr-upper', 'all-upper CashAddr (valid)'),
	// Token-aware CashAddr (CashTokens upgrade): types 2 and 3 are standard
	// mainnet destinations and accept plain BCH payments, so a merchant may
	// legitimately paste one. First is the published spec vector.
	array('BCH', 'bitcoincash:zr7fzmep8g7h7ymfxy74lgc0v950j3r295z4y4gq0v', 'cashaddr', 'token-aware P2PKH (spec vector)'),
	array('BCH', t_cashaddr_encode('bitcoincash', 2, $cashAddrSpecHash), 'cashaddr', 'token-aware P2PKH (generated)'),
	array('BCH', t_cashaddr_encode('bitcoincash', 3, $cashAddrSpecHash), 'cashaddr', 'token-aware P2SH (generated)'),

	// DGB: shares P2PKH version 0x1e with DOGE, S-form P2SH 0x3f, dgb1 segwit
	array('DGB', 'D596YFweJQuHY1BbjazZYmAbt8jJPbKehC', 'b58', 'zero-hash P2PKH (0x1e)'),
	array('DGB', t_b58check_encode("\x3f", $zeros20), 'b58', 'generated P2SH (0x3f)'),
	array('DGB', t_bech32_encode('dgb', 0, $bip173Program, false), 'bech32', 'generated P2WPKH'),

	// QTUM / XMY / BTX (pinned zero-hash vectors)
	array('QTUM', 'QLbz7JHiBTspS962RLKV8GndWFwiJNvEPz', 'b58', 'zero-hash P2PKH (0x3a)'),
	array('XMY', 'M7uAERuQW2AotfyLDyewFGcLUDtAYu9v5V', 'b58', 'zero-hash P2PKH (0x32)'),
	array('BTX', '2D1oxKts8YPdTJRG5FzxTNpMtWmqBnjrht', 'b58', 'zero-hash P2PKH (0x03)'),

	// Every remaining address family the chain parameters define. Each of
	// these was rejected before - a merchant pasting one would have had it
	// stripped on save with "no valid wallet addresses".
	array('QTUM', t_b58check_encode("\x32", $zeros20), 'b58', 'generated P2SH (0x32)'),
	array('QTUM', t_bech32_encode('qc', 0, $bip173Program, false), 'bech32', 'generated P2WPKH (qc1)'),
	array('XMY', t_b58check_encode("\x09", $zeros20), 'b58', 'generated P2SH (0x09)'),
	array('XMY', t_bech32_encode('my', 0, $bip173Program, false), 'bech32', 'generated P2WPKH (my1)'),
	array('ONION', t_b58check_encode("\x1f", $zeros20), 'b58', 'generated P2PKH (0x1f)'),
	array('ONION', t_b58check_encode("\x4e", $zeros20), 'b58', 'generated P2SH (0x4e)'),
	array('ONION', t_bech32_encode('dpn', 0, $bip173Program, false), 'bech32', 'generated P2WPKH (dpn1)'),
	array('VRC', t_b58check_encode("\x46", $zeros20), 'b58', 'generated P2PKH (0x46)'),
	array('VRC', t_b58check_encode("\x84", $zeros20), 'b58', 'generated P2SH (0x84)'),
	array('POT', t_b58check_encode("\x37", $zeros20), 'b58', 'generated P2PKH (0x37)'),
	array('POT', t_b58check_encode("\x05", $zeros20), 'b58', 'generated P2SH (0x05)'),

	// TRX (base58check version 0x41) - well-known USDT contract address form
	array('TRX', 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t', 'b58', 'base58check (0x41)'),
	array('USDTTRX', 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t', 'b58', 'base58check (0x41)'),

	// BLK: base58check (0x19 'B...') plus native segwit - BlackCoin
	// activated segwit on mainnet (March 2026); blackcoin-more v26.2.0
	// chain params define bech32 hrp 'blk'
	array('BLK', t_b58check_encode("\x19", $zeros20), 'b58', 'generated P2PKH (0x19)'),
	array('BLK', t_bech32_encode('blk', 0, $bip173Program, false), 'bech32', 'generated P2WPKH (hrp blk)'),

	// XTZ implicit accounts: tz1..tz3 plus tz4 (BLS), all valid payment
	// destinations. Vectors constructed with the test-side base58check
	// encoder over the documented 3-byte prefixes (tz1 = 06a19f,
	// tz4 = 06a1a6) + 20 zero bytes - structurally exact 36-char
	// addresses; XTZ validation is anchored-pattern-only (no SHA256d
	// checksum in scope), so the zero payload is irrelevant
	array('XTZ', t_b58check_encode("\x06\xa1\x9f", $zeros20), 'pattern', 'generated tz1 (Ed25519)'),
	array('XTZ', t_b58check_encode("\x06\xa1\xa6", $zeros20), 'pattern', 'generated tz4 (BLS)'),

	// ADA: Shelley bech32 (CIP-19 test vector; the old pattern wrongly
	// rejected every Shelley address)
	array('ADA', 'addr1qx2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3n0d3vllmyqwsx5wktcd8cc3sq835lu7drv2xwl2wywfgse35a3x', 'bech32', 'CIP-19 Shelley base address'),

	// pattern-only schemes (no verifiable SHA256d checksum - see NMM_Address)
	array('ETH', '0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe', 'hex', 'Ethereum Foundation'),
	array('XRP', 'rN7n7otQDd6FczFgLdSqtcsAUxDkw6fzRH', 'pattern', 'classic address'),
	array('XMR', '44AFFq5kSiGBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVGQBEP3A', 'pattern', 'donation address (95 chars)'),
	array('SOL', 'So11111111111111111111111111111111111111112', 'pattern', 'wrapped-SOL mint'),
);

// mutation/truncation-must-fail applies to CHECKSUMMED schemes only; 'hex'
// (EVM) has no verifiable checksum without EIP-55/keccak (out of scope) and
// gets its own documented-limit checks below
$mutationCharset = array('b58' => $B58, 'bech32' => $B32, 'cashaddr' => $B32);

foreach ($valid as $v) {
	list($coin, $address, $scheme, $note) = $v;

	check($coin, $address, true, 'valid ' . $note);

	// hostile affixes must fail for EVERY coin - this is the anchoring fix
	check($coin, $address . '?x=1', false, 'query-suffixed');
	check($coin, $address . ' trailing', false, 'word-suffixed');
	check($coin, 'hello ' . $address, false, 'word-prefixed');

	// checksummed schemes: one-char mutation and truncation must fail
	if (isset($mutationCharset[$scheme])) {
		check($coin, t_mutate($address, $mutationCharset[$scheme]), false, 'one-char-mutated');
		check($coin, substr($address, 0, -1), false, 'truncated');
	}
}

// pattern-only truncation: fixed-length schemes must fail; variable-length
// schemes (SOL 32-44, XRP 25-35) cannot catch a one-char truncation by
// design - documented here so the limitation is explicit, not accidental
check('ETH', substr('0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe', 0, -1), false, 'truncated (fixed length)');
check('XMR', substr('44AFFq5kSiGBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVGQBEP3A', 0, -1), false, 'truncated (fixed length)');
check('SOL', substr('So11111111111111111111111111111111111111112', 0, -1), true, 'truncated stays in 32-44 range (pattern limit)');
check('ETH', t_mutate('0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAe', $HEX), true, 'mutation undetectable without EIP-55 (documented limit)');

// XTZ is fixed-length (36) so truncation fails; a same-charset mutation is
// undetectable without the (out-of-scope) checksum - documented limit
$tz4 = t_b58check_encode("\x06\xa1\xa6", $zeros20);
aok('XTZ generated vector really is a tz4 (prefix bytes pinned)', strpos($tz4, 'tz4') === 0 && strlen($tz4) === 36, $tz4);
check('XTZ', substr($tz4, 0, -1), false, 'truncated tz4 (fixed length)');
check('XTZ', t_mutate($tz4, $B58), true, 'tz4 mutation undetectable without checksum (documented limit)');
check('XTZ', 'tz5' . substr($tz4, 3), false, 'unknown tz5 prefix');

// ---------------------------------------------------------------------
// wrong-network vectors: checksum-VALID testnet addresses must fail on
// the version byte / hrp / prefix, not merely on the checksum
// ---------------------------------------------------------------------

check('BTC', t_b58check_encode("\x6f", $zeros20), false, 'testnet P2PKH (0x6f, checksum ok)');
check('BTC', t_b58check_encode("\xc4", $zeros20), false, 'testnet P2SH (0xc4, checksum ok)');
check('BTC', 'mipcBbFg9gMiCh81Kj8tqqdgoZub1ZJRfn', false, 'well-known testnet P2PKH');
check('BTC', t_bech32_encode('tb', 0, $bip173Program, false), false, 'testnet hrp tb (checksum ok)');
check('LTC', t_b58check_encode("\x6f", $zeros20), false, 'testnet P2PKH (checksum ok)');
check('LTC', t_bech32_encode('tltc', 0, $bip173Program, false), false, 'testnet hrp tltc (checksum ok)');
check('DOGE', t_b58check_encode("\x71", $zeros20), false, 'testnet P2PKH (0x71, checksum ok)');
check('DASH', t_b58check_encode("\x8c", $zeros20), false, 'testnet P2PKH (0x8c, checksum ok)');
check('DGB', t_b58check_encode("\x7e", $zeros20), false, 'testnet P2PKH (checksum ok)');
check('BCH', t_b58check_encode("\x6f", $zeros20), false, 'testnet legacy (checksum ok)');
check('BCH', 'bchtest:qpm2qsznhks23z7629mms6s4cwef74vcwvy22gdx6a', false, 'testnet CashAddr prefix');
check('TRX', t_b58check_encode("\xa0", $zeros20), false, 'testnet version (0xa0, checksum ok)');

// cross-coin version bytes must not be interchangeable
check('DOGE', 'XagqqFetxiDb9wbartKDrXgnqLah6SqX2S', false, 'DASH address rejected for DOGE');
check('DASH', 'D596YFweJQuHY1BbjazZYmAbt8jJPbKehC', false, 'DOGE address rejected for DASH');
check('BTC', 'LKDxGDJq5fF4FohAB8zJH24mDDNHDNtqsE', false, 'LTC address rejected for BTC');
check('BTC', t_bech32_encode('ltc', 0, $bip173Program, false), false, 'ltc1 rejected for BTC');
check('BLK', t_bech32_encode('bc', 0, $bip173Program, false), false, 'bc1 rejected for BLK (checksum ok, wrong hrp)');
check('BTC', t_bech32_encode('blk', 0, $bip173Program, false), false, 'blk1 rejected for BTC (checksum ok, wrong hrp)');
check('BLK', t_bech32_encode('tblk', 0, $bip173Program, false), false, 'testnet hrp tblk (checksum ok)');

// ---------------------------------------------------------------------
// bech32 vs bech32m discipline (BIP-350) and case rules
// ---------------------------------------------------------------------

check('BTC', t_bech32_encode('bc', 0, $bip173Program, true), false, 'witness v0 with bech32m checksum');
check('BTC', t_bech32_encode('bc', 1, $xonly, false), false, 'witness v1 with bech32 checksum');
check('BTC', 'bC1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4', false, 'mixed-case bech32');
check('BTC', 'bc1Qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4', false, 'mixed-case bech32 (data part)');
check('BCH', 'bitcoincash:Qpm2qsznhks23z7629mms6s4cwef74vcwvy22gdx6a', false, 'mixed-case CashAddr');

// Token-aware CashAddr boundary: BCH opted in at the CashTokens upgrade, BSV
// forked before it and never adopted these types, so the same string must be
// accepted for one coin and refused for the other. Type 4+ is undefined for
// both - accepting it would let a typo'd version byte through.
// ONION pins its two documented version bytes instead of accepting any
// version behind a 'D' prefix. Versions 30 and 32 also render as 'D', so the
// old rule validated a DOGE address pasted into the DeepOnion field - funds to
// an address on a chain that never sees them.
check('ONION', t_b58check_encode("\x1e", $zeros20), false, 'DOGE address (version 30, renders as D)');
check('ONION', t_b58check_encode("\x20", $zeros20), false, 'version 32 (also renders as D)');
check('ONION', t_bech32_encode('bc', 0, $bip173Program, false), false, 'BTC bech32 rejected for ONION');
check('QTUM', t_bech32_encode('bc', 0, $bip173Program, false), false, 'BTC bech32 rejected for QTUM');
check('XMY', t_bech32_encode('qc', 0, $bip173Program, false), false, 'QTUM bech32 rejected for XMY');
check('VRC', t_b58check_encode("\x85", $zeros20), false, 'version 133 (adjacent to p2sh 132)');
check('POT', t_b58check_encode("\x38", $zeros20), false, 'version 56 (also renders as P)');
check('POT', t_b58check_encode("\x39", $zeros20), false, 'version 57 (also renders as P)');

check('BSV', 'bitcoincash:zr7fzmep8g7h7ymfxy74lgc0v950j3r295z4y4gq0v', false, 'token-aware P2PKH rejected for BSV (spec vector)');
check('BSV', t_cashaddr_encode('bitcoincash', 2, $cashAddrSpecHash), false, 'token-aware P2PKH rejected for BSV');
check('BSV', t_cashaddr_encode('bitcoincash', 3, $cashAddrSpecHash), false, 'token-aware P2SH rejected for BSV');
check('BSV', t_cashaddr_encode('bitcoincash', 0, $cashAddrSpecHash), true, 'plain CashAddr still valid for BSV');
check('BCH', t_cashaddr_encode('bitcoincash', 4, $cashAddrSpecHash), false, 'undefined type 4 (checksum ok)');
check('BCH', t_cashaddr_encode('bitcoincash', 15, $cashAddrSpecHash), false, 'undefined type 15 (checksum ok)');

// the exact strings the finding demonstrated as wrongly accepted
check('BTC', 'hello bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4', false, "finding: 'hello bc1q...'");
check('BTC', '1A1zP1eP5QGefi2DMPTfTL5SLmv7Div', false, 'finding: truncated BTC');
check('DOGE', 'D596YFweJQuHY1BbjazZYmAbt8jJPbKehD', false, 'finding: bad-checksum DOGE');

// ---------------------------------------------------------------------
// EVM tokens route through the shared 0x check
// ---------------------------------------------------------------------

check('USDT', '0xdAC17F958D2ee523a2206206994597C13D831ec7', true, 'token address form');
check('USDT', '0xdAC17F958D2ee523a2206206994597C13D831ec', false, 'token address truncated');
check('USDT', '0xdAC17F958D2ee523a2206206994597C13D831ec7aa', false, '42 hex chars (old {40,42} bug)');
check('USDC', 'hello 0xdAC17F958D2ee523a2206206994597C13D831ec7', false, 'token address prefixed');
check('ETH', '0xde0B295669a9FD93d5F28D9Ec85E40f4cb697BAeff', false, '42 hex chars (old {40,42} bug)');

// ---------------------------------------------------------------------
// odds and ends: empty / non-string / whitespace-only always fail
// ---------------------------------------------------------------------

check('BTC', '', false, 'empty');
check('BTC', '   ', false, 'whitespace only');
check('SOL', '', false, 'empty');
check('EOS', 'binanceclean', true, 'valid 12-char account');
check('EOS', 'Binancecleos', false, 'uppercase account name');
check('EOS', 'waytoolongaccount', false, '13+ chars');
check('XLM', 'GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7', true, 'strkey (56 chars)');
check('XLM', 'GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN', false, 'truncated strkey');

printf("\n%d checks, %s\n", $nChecks, $failed ? 'FAILURES PRESENT' : 'all passed');
exit($failed ? 1 : 0);
